name: CI Pipeline

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:  # Run on pull requests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup - Check out code
        uses: actions/checkout@v3

      - name: Setup - Download Conda
        run: |
          # Step 1: Download and install Miniconda (if not already installed)
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda

          # Step 2: Add Miniconda to the PATH
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH

      - name: Setup - List Conda Environments
        run: |
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda info --envs

      - name: Setup - Conda Venv
        run: |
          # Step 3: Create the Conda environment
          conda create --name tcr_embeddings python=3.12 -y
          conda env list

      - name: Setup - Activate Conda
        run: |
          # Step 4: Activate the Conda environment
          source $HOME/miniconda/etc/profile.d/conda.sh  # This ensures conda works in the current shell
          conda activate tcr_embeddings

      - name: Setup - Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install


      - name: Check - Code Formatting
        run: black . --check

      - name: Check - Import Order
        run: isort . --check --diff

      - name: Linting - flake8
        run: flake8 .

      - name: Check - Types
        run: mypy .

      - name: Check - Unit Tests
        run: python -m unittest discover -s tests -p "*.py"
