name: CI Pipeline

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:  # Run on pull requests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Conda environment
        run: |
          # Step 1: Download and install Miniconda (if not already installed)
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda

          # Step 2: Add Miniconda to the PATH
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH

          # Step 3: Create the Conda environment
          conda create --name tcr_embeddings python=3.12 -y

          # Step 4: Activate the Conda environment
          source $HOME/miniconda/etc/profile.d/conda.sh  # This ensures conda works in the current shell
          conda activate tcr_embeddings

          # Step 5: Install dependencies
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install


      - name: Check code formatting with black
        run: black . --check

      - name: Check import order with isort
        run: isort . --check --diff

      - name: Run flake8 linting
        run: flake8 .

      - name: Run mypy type checking
        run: mypy .

      - name: Run unit tests with pytest
        run: python -m unittest discover -s tests -p "*.py"
