name: CI Pipeline

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:  # Run on pull requests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup - Check out code
        uses: actions/checkout@v3

      - name: Setup - Download Conda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH

      - name: Setup - List Conda Environments
        run: |
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda info --envs

      - name: Setup - Conda Venv
        run: |
          conda create --name tcr_embeddings python=3.12 -y
          conda env list

      - name: Setup - Activate Conda
        run: |
          source $HOME/miniconda/etc/profile.d/conda.sh  # This ensures conda works in the current shell
          conda activate tcr_embeddings

      - name: Setup - Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install

      - name: Setup - CI/CD Packages
        run: |
          python -m pip install black isort flake8 flake8-pyproject mypy

      - name: Check - Code Formatting [black]
        run: black . --check

      - name: Check - Import Order [isort]
        run: isort . --check --diff

      - name: Check - Linting [flake8]
        run: flake8 .

      - name: Check - Types [mypy]
        run: mypy --ignore-misisng-imports --config-file pyproject.toml .

      - name: Check - Unit Tests [unittest]
        run: python -m unittest discover -s test -p "*test*.py" -v
